#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: tap-gitops/tap-install
    kapp.k14s.io/change-rule.create-order: upsert after upserting tap-gitops/tap-repo
    kapp.k14s.io/change-rule.delete-order: delete before deleting tap-gitops/tap-repo
type: Opaque
stringData:
  username: git
  password: #@ data.values.github.accessToken
