#@ load("@ytt:data", "data")
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: tap
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: tap-gitops/tap-install
    kapp.k14s.io/change-rule.create-order: upsert after upserting tap-gitops/tap-repo
    kapp.k14s.io/change-rule.delete-order: delete before deleting tap-gitops/tap-repo
spec:
  syncPeriod: 10m
  serviceAccountName: tap-install-gitops-sa
  packageRef:
    refName: tap.tanzu.vmware.com
    versionSelection:
      constraints: #@ "{}".format(data.values.tap.version)
      prereleases: { }
  values:
  - secretRef:
      name: tap-install-values
