apiVersion: v1
kind: ServiceAccount
metadata:
  name: tap-install-gitops-sa
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: tap-gitops/tap-rbac
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tap-install-gitops-cluster-role
  annotations:
    kapp.k14s.io/change-group: tap-gitops/tap-rbac
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tap-install-gitops-cluster-role-binding
  annotations:
    kapp.k14s.io/change-group: tap-gitops/tap-rbac
subjects:
- kind: ServiceAccount
  name: tap-install-gitops-sa
  namespace: tap-install
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tap-install-gitops-cluster-role
