#@ load("@ytt:data", "data")
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: tanzu-tap-repository
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: tap-gitops/tap-repo
    kapp.k14s.io/change-rule.create-order: upsert after upserting tap-gitops/tap-rbac
    kapp.k14s.io/change-rule.delete-order: delete before deleting tap-gitops/tap-rbac
spec:
  fetch:
    imgpkgBundle:
      image: #@ "{}/{}/tap-packages:{}".format(data.values.tap.registry.hostname, data.values.tap.registry.repo, data.values.tap.version)
